=== Victor-Picallo/XMLciclo1/Ejercicio5LIBRO/libro.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Elemento raiz -->
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" type="tipoLibro" maxOccurs="unbounded"/>
                <xs:element name="prestamo" type="tipoPrestamo" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Elemento tipolibro -->
        <xs:complexType name="tipoLibro">
            <xs:sequence>
                <xs:element ref="titulo"/>
                <xs:element ref="autor"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>


    <!-- elemento tipoprestamo -->
        <xs:complexType name="tipoPrestamo">
            <xs:sequence>
                <xs:element ref="fecha"/>
            </xs:sequence>
            <xs:attribute name="libro" type="xs:IDREF" use="required"/>
        </xs:complexType>


    <!-- elemento titulo -->
    <xs:element name="titulo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="50"/>
                <xs:minLength value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- elemento autor -->
    <xs:element name="autor">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="50"/>
                <xs:minLength value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- elemento fecha -->
    <xs:element name="fecha" type="xs:date"/>
</xs:schema>

=== Victor-Picallo/XMLciclo1/Ejercicio5LIBRO/libro.xml
<?xml version="1.0" encoding="UTF-8" ?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="libro.xsd">
    <libro id="1001">
        <titulo>El principito</titulo>
        <autor>Antoine de Saint-Exupery</autor>
    </libro>

    <libro id="1002">
        <titulo>Cien años de soledad</titulo>
        <autor>Gabriel Garcia Marquez</autor>
    </libro>

    <libro id="1003">
        <titulo>El amor en los tiempos del cólera</titulo>
        <autor>Gabriel Garcia Marquez</autor>
    </libro>

    <prestamo libro="1001">
        <fecha>2025-01-05</fecha>
    </prestamo>

    <prestamo libro="1002">
        <fecha>2025-01-10</fecha>
    </prestamo>

    <prestamo libro="1003">
        <fecha>2025-01-15</fecha>
    </prestamo>
</catalogo>
