=== Victor-Picallo/XMLciclo1/Ejercicio6Lenguaje/ejercicio.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Programacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Lenguaje" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Lenguaje">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Nombre"/>
                <xs:element ref="Creador"/>
                <xs:element ref="AnioCreacion"/>
                <xs:element ref="Descripcion"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Nombre">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Python"/>
                <xs:enumeration value="Java"/>
                <xs:enumeration value="C++"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Creador" type="xs:string"/>

    <xs:element name="AnioCreacion">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1950"/>
                <xs:maxInclusive value="2025"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Descripcion">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="255"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== Victor-Picallo/XMLciclo1/Ejercicio6Lenguaje/ejercicio.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Programacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="ejercicio.xsd">
    <Lenguaje>
        <Nombre>Python</Nombre>
        <Creador>Guido van Rossum</Creador>
        <AnioCreacion>1991</AnioCreacion>
        <Descripcion>Python is a high-level, interpreted, and general-purpose
        programming language that emphasizes readability with its notable use of
        significant whitespace.</Descripcion>
    </Lenguaje>
    <Lenguaje>
        <Nombre>Java</Nombre>
        <Creador>James Gosling</Creador>
        <AnioCreacion>1995</AnioCreacion>
        <Descripcion>Java is a class-based, object-oriented programming language
        that is designed to hace as few implementation dependencies as possible.</Descripcion>
    </Lenguaje>
    <Lenguaje>
        <Nombre>C++</Nombre>
        <Creador>Bjarne Stroustrup</Creador>
        <AnioCreacion>1985</AnioCreacion>
        <Descripcion>C++ is a general-purpose programming language
        created as an extension of the C programming language, or "C with Classes"</Descripcion>
    </Lenguaje>
</Programacion>
